on: 
 workflow_dispatch:

jobs:
  oryx_build_job:
    runs-on: ubuntu-latest
    name: A job to run Oryx build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Oryx build step
        uses: ./ # Uses an action in the root directory
        id: oryx-build
        with:
          app-location: "Client"
  Deploy-preview:
    runs-on: ubuntu-latest
    steps:   
      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Build Project Artifacts
        run: vercel build         