on: 
 workflow_dispatch:

jobs:
  oryx_build_job:
    runs-on: ubuntu-latest
    name: A job to run Oryx build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Azure-cli
        uses: elstudio/action-install-azure-cli@v1
      - name: Log into registry
        uses: azure/login@v1
        with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2.0.0
        with: 
         registry: jamstacktest.azurecr.io
         username: ${{ secrets.AZURE_CLIENT_ID }}
         password: ${{ secrets.AZURE_CLIENT_SECRET }}   
      - name: Oryx build step
        uses: ./ # Uses an action in the root directory
        id: oryx-build
        with:
          app-location: "Client"
  Deploy-preview:
    runs-on: ubuntu-latest
    steps:   
      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run:  vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} 
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}   